spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

multitenancy:
  tenants:
    tenant1:
      url: jdbc:h2:mem:tenant1_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver
    tenant2:
      url: jdbc:h2:mem:tenant2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  metrics:
    enable:
      system: false # ProcessorMetrics 비활성화
      processor: false

jwt:
  secret: QLS1ydgZDSmNXc6TK85m1YuhHN41tRc53Vbvo6CIowk=
  validity: 7200000 # 2시간
  expiration: 3600000
# openssl rand -base64 32
# openssl rand -base64 64

logging:
  level:
    org.springframework: DEBUG
    com.hy: DEBUG
    org.springframework.cloud.config: TRACE
    org.springframework.boot.actuate: TRACE
    io.micrometer: DEBUG
    org.springframework.beans: TRACE
    org.springframework.context: TRACE
