spring:
  profiles:
    active: prod
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
multitenancy:
  tenants:
    tenant1:
      url: jdbc:h2:mem:tenant1_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver
    tenant2:
      url: jdbc:h2:mem:tenant2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver
jwt:
  secret: ${JWT_SECRET:your-default-secret-key}
  validity: 3600000
