server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyeyeonDev/spring-config-repo
          default-label: main
          clone-on-start: true
          force-pull: true
          # timeout: 10
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
