server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  metrics:
    enable:
      process: false
      system: false