server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-test
          uri: lb://user-service
          predicates:
            - Path=/test/**
        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<remaining>.*), /auth/${remaining}
#        - id: raffle-service
#          uri: lb://raffle-service
#          predicates:
#            - Path=/raffle/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, refresh