spring:
  application:
    name: multi-tenant-core

multitenancy:
  tenants:
    tenant1:
      url: jdbc:h2:mem:tenant1_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver
    tenant2:
      url: jdbc:h2:mem:tenant2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      driver-class-name: org.h2.Driver
