spring:
  application:
    name: security-common

jwt:
  secret: QLS1ydgZDSmNXc6TK85m1YuhHN41tRc53Vbvo6CIowk=
  validity: 7200000 # 2시간
  expiration: 3600000
# openssl rand -base64 32
# openssl rand -base64 64
