server:
  port: 8081

spring:
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
---
spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:security_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
# multitenancy:
#   tenants:
#     tenant1:
#       url: jdbc:h2:mem:tenant1_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#       username: sa
#       password: ''
#       driver-class-name: org.h2.Driver
#     tenant2:
#       url: jdbc:h2:mem:tenant2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#       username: sa
#       password: ''
#       driver-class-name: org.h2.Driver

# jwt:
#   secret: QLS1ydgZDSmNXc6TK85m1YuhHN41tRc53Vbvo6CIowk=
#   validity: 7200000
