server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
  datasource:
    url: jdbc:h2:mem:security_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

# multitenancy:
#   datasources:
#     tenant1:
#       url: jdbc:h2:mem:tenant1;DB_CLOSE_DELAY=-1
#       username: sa
#       password:
#       driverClassName: org.h2.Driver
#     tenant2:
#       url: jdbc:h2:mem:tenant2;DB_CLOSE_DELAY=-1
#       username: sa
#       password:
#       driverClassName: org.h2.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: QLS1ydgZDSmNXc6TK85m1YuhHN41tRc53Vbvo6CIowk=
  expiration: 3600000
# openssl rand -base64 32
# openssl rand -base64 64
